const PBKDF2_ITERATIONS = 100000;
const PBKDF2_DIGEST = 'sha256';
const SALT_LENGTH = 16;
const NONCE_LENGTH = 24;
const KEY_LENGTH = 32;
const MIN_PASSWORD_LENGTH = 8;
const MAX_PASSWORD_LENGTH = 128;
const PACKAGE_VERSION = '1.0.0';
const DEP_TWEETNACL_VERSION = '1.0.3';
const ENCODING = 'base64';

module.exports = {
  PBKDF2_ITERATIONS,
  PBKDF2_DIGEST,
  SALT_LENGTH,
  NONCE_LENGTH,
  KEY_LENGTH,
  MIN_PASSWORD_LENGTH,
  MAX_PASSWORD_LENGTH,
  PACKAGE_VERSION,
  DEP_TWEETNACL_VERSION,
  ENCODING,
};
